dnsmasq:
  restart: always
  image: andyshinn/dnsmasq
  container_name: dnsmasq
  ports:
    - "53:53/udp"
    - "53:53/tcp"
  extra_hosts:  
    - "hogehoge.local:192.168.1.13"
  cap_add:
    - NET_ADMIN
